const PRODUCTS = [
  {
    id: "gl-apex-16",
    name: "Apex 16 Pro",
    brand: "BestLaptop",
    category: "gaming",
    price: 3399000,
    oldPrice: 3720000,
    cpu: "Ryzen 9",
    ram: "32GB",
    storage: "1TB",
    stock: 7,
    tag: "الأكثر مبيعاً",
    specs: "RTX 4070 · Ryzen 9 · 32GB · 1TB",
    screen: "16 بوصة 240Hz",
    gpu: "RTX 4070",
    tgp: "140W",
    cooling: "تبريد مزدوج",
    headline: "أداء تنافسي يومي بدون اختناق حراري",
    blurb: "كرت RTX 4070 بشاشة 240Hz وذاكرة 32GB للعب والمونتاج في جهاز واحد.",
    slide: true,
    image:
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "gl-phantom-15",
    name: "Phantom 15",
    brand: "BestLaptop",
    category: "gaming",
    price: 2520000,
    oldPrice: 2760000,
    cpu: "Core i7",
    ram: "16GB",
    storage: "1TB",
    stock: 12,
    tag: "قيمة ممتازة",
    specs: "RTX 4060 · Core i7 · 16GB · 1TB",
    screen: "15.6 بوصة 165Hz",
    gpu: "RTX 4060",
    tgp: "115W",
    cooling: "مراوح مزدوجة",
    image:
      "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "gl-titan-18",
    name: "Titan 18 Ultra",
    brand: "BestLaptop",
    category: "gaming",
    price: 5200000,
    oldPrice: 5800000,
    cpu: "Core i9",
    ram: "64GB",
    storage: "2TB",
    stock: 3,
    tag: "ملك الأداء",
    specs: "RTX 4080 · Core i9 · 64GB · 2TB",
    screen: "18 بوصة Mini-LED",
    gpu: "RTX 4080",
    tgp: "175W",
    cooling: "غرفة بخار",
    headline: "قمة الأداء للرندر واللعب على شاشة 18 بوصة",
    blurb: "Mini-LED بتردد عالٍ وكرت بكامل الواط مع ذاكرة 64GB للجلسات الطويلة.",
    slide: true,
    image:
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "gl-nova-14",
    name: "Nova 14 Compact",
    brand: "BestLaptop",
    category: "gaming",
    price: 2200000,
    oldPrice: null,
    cpu: "Ryzen 7",
    ram: "16GB",
    storage: "512GB",
    stock: 0,
    tag: "محمول",
    specs: "RTX 4050 · Ryzen 7 · 16GB · 512GB",
    screen: "14 بوصة 144Hz",
    gpu: "RTX 4050",
    tgp: "75W",
    cooling: "هادئ",
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "pr-studio-16",
    name: "Studio 16 Creator",
    brand: "BestLaptop",
    category: "production",
    price: 3680000,
    oldPrice: 4000000,
    cpu: "Core i9",
    ram: "32GB",
    storage: "2TB",
    stock: 6,
    tag: "للمونتاج",
    specs: "RTX 4070 · Core i9 · 32GB · 2TB",
    screen: "16 بوصة OLED 4K",
    gpu: "RTX 4070",
    tgp: "140W",
    cooling: "صامت نسبياً",
    headline: "ألوان سينمائية على OLED للمونتاج والتصميم",
    blurb: "تغطية لونية عالية وذاكرة واسعة لتصدير 4K دون انتظار مزعج.",
    slide: true,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "pr-frame-15",
    name: "Frame 15 Edit",
    brand: "BestLaptop",
    category: "production",
    price: 2960000,
    oldPrice: 3200000,
    cpu: "Ryzen 9",
    ram: "32GB",
    storage: "1TB",
    stock: 8,
    tag: "موصى به",
    specs: "RTX 4060 · Ryzen 9 · 32GB · 1TB",
    screen: "15.6 بوصة 100% DCI-P3",
    gpu: "RTX 4060",
    tgp: "115W",
    cooling: "متوازن",
    image:
      "https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "pr-canvas-14",
    name: "Canvas 14 Air",
    brand: "BestLaptop",
    category: "production",
    price: 2360000,
    oldPrice: null,
    cpu: "Core Ultra 7",
    ram: "32GB",
    storage: "1TB",
    stock: 11,
    tag: "خفة وزن",
    specs: "Arc Graphics · Core Ultra 7 · 32GB · 1TB",
    screen: "14 بوصة OLED",
    gpu: "Arc",
    tgp: "28W",
    cooling: "مروحة واحدة",
    image:
      "https://images.unsplash.com/photo-1511385348-a52b4a160dc2?auto=format&fit=crop&w=1400&q=80",
  },
  {
    id: "pr-render-17",
    name: "Render 17 Workstation",
    brand: "BestLaptop",
    category: "production",
    price: 6200000,
    oldPrice: 6800000,
    cpu: "Xeon",
    ram: "64GB",
    storage: "4TB",
    stock: 2,
    tag: "محطة عمل",
    specs: "RTX 5000 Ada · Xeon · 64GB · 4TB",
    screen: "17 بوصة 4K Adobe RGB",
    gpu: "RTX 5000",
    tgp: "175W",
    cooling: "محطة عمل",
    image:
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1400&q=80",
  },
];

const SLIDES = [];
const PRODUCT_SLIDERS = [];
const BRANDS = [];

const STORE = {
  name: "BEST LAPTOP",
  nameAr: "بيست لابتوب",
  logo: "img/logo.jpg",
  notice: "بغداد · شارع الصناعة، مجمع النعمان، الطابق الثاني · ضمان سنتين حقيقي",
  city: "بغداد",
  address: "شارع الصناعة، مجمع النعمان، الطابق الثاني",
  fullAddress: "العراق، بغداد — شارع الصناعة، مجمع النعمان، الطابق الثاني",
  phone: "0772 222 4489",
  whatsapp: "0772 222 4489",
  email: "support@bestlaptop.iq",
  hours: "السبت – الخميس: 9:30 ص – 8:30 م",
  warranty: "ضمان سنتين حقيقي معتمد",
  maintenanceMode: false,
  maintenanceMessage: "",
  currency: "IQD",
  cities: [
    "بغداد",
    "البصرة",
    "الموصل",
    "أربيل",
    "النجف",
    "كربلاء",
    "بابل",
    "الأنبار",
    "ديالى",
    "واسط",
    "صلاح الدين",
    "كركوك",
    "ذي قار",
    "ميسان",
    "المثنى",
    "القادسية",
    "دهوك",
    "السليمانية",
  ],
  shipping: [
    {
      id: "baghdad",
      label: "توصيل بغداد",
      fee: 10000,
      hint: "توصيل داخل بغداد خلال يوم عمل",
    },
    {
      id: "governorate",
      label: "توصيل المحافظات",
      fee: 10000,
      hint: "توصيل خارج بغداد خلال 2–4 أيام",
    },
  ],
  payments: [
    {
      id: "cod",
      label: "الدفع عند الاستلام",
      hint: "ادفع نقداً عند استلام الطلب",
    },
    {
      id: "office",
      label: "الدفع في المعرض",
      hint: "ادفع في المعرض عند زيارتك",
    },
  ],
  featured: {
    eyebrow: "الأكثر مبيعاً",
    title: "منتجات مميزة للقيمنق والمونتاج",
    category: "all",
    limit: 8,
  },
  officeGallery: {
    active: true,
    title: "من داخل مكتب بيست لابتوب",
    images: {
      wide: "",
      tall: "",
      bottomStart: "",
      bottomEnd: "",
    },
  },
};

const CATEGORIES = [
  { id: "gaming", title: "لابتوبات القيمنق", text: "شاشات عالية التردد وكروت RTX" },
  { id: "production", title: "لابتوبات الإنتاج", text: "OLED ودقة ألوان للمونتاج" },
  { id: "oled", title: "شاشات OLED", text: "تغطية لونية للمصممين" },
  { id: "workstation", title: "محطات العمل", text: "ذاكرة واسعة ورندر ثقيل" },
];
